### ISSUE TITLE
[Question/Help] Is it possible to use this mvn based library with an Ant based Project?

### ISSUE THREAD

**Issue by kRystalDevv** [umjammer/mp3spi#13]
I'm working on a project using Ant, and I need to incorporate MP3 playback and control. I came across this mp3spi library, which is based on Maven. Since I'm new to this, I'm unsure if I can use mp3spi in my Ant-based project. Additionally, I'm open to suggestions for alternative approaches to control playback and seeking. Any guidance would be greatly appreciated.

Using:
- Netbeans 17
- Java 8
- Ant

**Comment by umjammer** [comment]
it's possible by ant.
but it's bothersome to prepare all jars written in [pom.xml dependencies section](https://github.com/umjammer/mp3spi/blob/master/pom.xml#L70-L98).

 * `tritonus` jars are found at https://github.com/umjammer?tab=packages&repo_name=tritonus
 * `vavi-commons` jar is found at https://jitpack.io/#umjammer/vavi-commons and [how to download](https://stackoverflow.com/a/69119619)
 * `juniversalchardet` jar is found at https://jitpack.io/#albfernandez/juniversalchardet

i highly recommend to use maven.

and see https://github.com/umjammer/jlayer/issues/5 for playback etc.
