### ISSUE TITLE
Is this project published on maven central?

### ISSUE THREAD

**Issue by kkocel** [umjammer/mp3spi#9]
I saw that the latest one has version 1.9.4: https://mvnrepository.com/artifact/net.javazoom/mp3spi

**Comment by umjammer** [comment]
i use [github packages](https://github.com/umjammer/mp3spi/packages/1067666) instead of maven central.
see [instruction](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry).

**Comment by schuettec** [comment]
But why?
It would be very useful if you would claim a namespace for Maven Central an publish artifacts there.

**Comment by umjammer** [comment]
this is a hobby project.
it's too troublesome for me to register maven central.

**Comment by umjammer** [comment]
repository has moved from github packages to **[jitpack](https://jitpack.io/#umjammer/mp3spi)**
